abouts/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index-about'),
]

blogs/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index-blog'),
    path('<slug:slug>/', views.detail, name='detail-blog'),
]

website_umroh/urls.py

from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('tentang-kami/', include('abouts.urls')),
    path('travel/', include('travels.urls')),
    path('blog/', include('blogs.urls')),
    path('paket/', include('packages.urls')),
    path('', include('homes.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Administrasi Taufiq Harohmain Tobah"
admin.site.site_title = "TAUFIQ HT TOURS & TRAVEL"
handler404 = 'website_umroh.views.handler_404'
handler500 = 'website_umroh.views.handler_500'

abouts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.safestring import mark_safe
from django.template.defaultfilters import truncatechars
from django.urls import reverse
from autoslug import AutoSlugField


class About(models.Model):
    deskripsi = models.TextField()
    visi_misi = models.TextField(
        verbose_name='Visi & Misi', null=True, blank=True)
    dibuat_pada = models.DateTimeField(auto_now_add=True)
    diperbarui_pada = models.DateTimeField(auto_now=True)

    def deskripsi_safe(self):
        return truncatechars(mark_safe(self.deskripsi), 200)

    class Meta:
        ordering = ('id',)
        verbose_name_plural = 'About Us'

    def get_absolute_url(self):
        return '/tentang-kami/'


class Service(models.Model):
    STATUS = (
        ('termasuk', 'Termasuk'),
        ('tidaktermasuk', 'Tidak Termasuk'),
    )
    about = models.ForeignKey(About, on_delete=models.CASCADE)
    nama = models.CharField(max_length=225, null=True, blank=True,
                            help_text='Biaya perjalanan termasuk/tidak-termasuk.')
    status = models.CharField(max_length=14, choices=STATUS)
    dibuat_pada = models.DateTimeField(auto_now_add=True)
    diperbarui_pada = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "%s - %s" % (self.id, self.nama)

    class Meta:
        ordering = ('id',)
        verbose_name_plural = ('services')


class PhotosActivity(models.Model):
    about = models.ForeignKey(About, on_delete=models.CASCADE)
    img = models.ImageField(upload_to='about_us/photos_of_activities',
                            null=True, blank=True, help_text='Foto Kegiatan.')
    dibuat_pada = models.DateTimeField(auto_now_add=True)
    diperbarui_pada = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "%s - %s" % (self.id, self.img.url)

    class Meta:
        ordering = ('id',)
        verbose_name_plural = ('photos of activities')

abouts/views.py
from django.shortcuts import render

from packages.models import PackageCategory
from travels.models import TravelCategory
from .models import *

def index(request):
    category_package = PackageCategory.objects.all()
    category_travel = TravelCategory.objects.all()

    abouts = About.objects.all()
    photos_activity = PhotosActivity.objects.all()
    context = {
        'abouts': abouts,
        'photos_activity': photos_activity,
        'category_package': category_package,
        'category_travel': category_travel,
    }
    template = 'abouts/index.html'
    return render(request,template,context)

abouts/templates/abouts/index.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<style>
    .responsive {
        width: 100%;
        height: auto
    }
</style>
<link rel="stylesheet" type="text/css" href="{% static 'abouts/css/styles.css' %}" />
{% endblock style %}

{% block main %}
<section id="main">
    <div class="pad-global">
        <div class="container" style="height: 30vw">
            <div class="row inline text-center">
                <div class="col inline l-9 m-10 s-12 product-animated-bottom">
                    <div class="t-global bold">Tentang Kami</div>
                    <div class="bdy-global">
                        {% if abouts %}
                        {% for obj in abouts %}
                        {{ obj.deskripsi|safe }}
                        {% endfor %}
                        {% else %}
                        <p>Belum Ada Deskripsi</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        <div class="pad-about">
            <div class="img-about product-animated-top">
                <!-- <img src="https://www.avia.travel/lib/images/photo/bg-about.jpg" /> -->
            </div>
            <div class="container mt-5">
                <div class="text-center product-animated-bottom">
                    <div class="t-global bold">Foto Kegiatan</div>


                    {% if photos_activity %}
                    <div class="slider-kegiatan">
                        {% for obj in photos_activity %}
                        <div class="item">
                            <a href="{{obj.img.url}}">
                                <div style="height: 30vw">
                                    <img src="{{obj.img.url}}" class="responsive" width="400" height="200" />
                                </div>
                            </a>
                        </div>
                        {% endfor %}
                    </div>
                    {% else %}
                    <div style="color: #666; margin: 5em 0">
                        <h5>Belum Ada Foto Kegiatan</h5>
                    </div>
                    {% endif %}
                </div>
            </div>
            <div class="bg-about" style="margin-bottom: 10rem">
                <div class="container">
                    <div class="t-global bold">Layanan</div>
                    <div class="tbl">
                        <div class="cell product-animated-left cell-top">
                            <div class="title-about">Termasuk</div>
                            <div class="bdy-tour">
                                <div class="bdy-about">
                                    <ul>
                                        {% if abouts %}
                                        {% for about in abouts %}
                                        {% for obj in about.service_set.all %}

                                        {% if obj.status == 'termasuk' %}
                                        <li>{{obj.nama}}</li>
                                        {% endif %}

                                        {% endfor %}
                                        {% endfor %}
                                        {% endif %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="cell product-animated-right cell-top">
                            <div class="title-about">Belum termasuk</div>
                            <div class="bdy-tour">
                                <div class="bdy-not-include">
                                    <ul>
                                        {% if abouts %}
                                        {% for about in abouts %}
                                        {% for obj in about.service_set.all %}

                                        {% if obj.status == 'tidaktermasuk' %}
                                        <li>{{obj.nama}}</li>
                                        {% endif %}
                                        {% endfor %}
                                        {% endfor %}
                                        {% endif %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="background-about"
                style="background: url('https://www.avia.travel/lib/images/photo/bg-about2.jpg') no-repeat center;">
                <div class="container">
                    <div class="row inline text-center">
                        <div class="col inline l-9 m-10 s-12 product-animated-bottom">
                            <div class="t-global bold">Kekuatan Perusahaan</div>
                            <div class="bdy-global center">
                                <p>Berlokasi strategis di pusat kota, terkenal dan telah memenuhi standard international
                                    sebuah perusahaan travel agent, dengan staff yang profesional dan ramah. Membuat
                                    anda merasa nyaman dalam menentukan pilihan layanan perusahaan. Berpengalaman dalam
                                    memanajemen perjalanan dan memilliki hubungan erat dengan berbagai penerbangan lokal
                                    dan internasional.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>


            <div class="pad-about">
                <div class="container mb30">
                    <div class="row inline text-center">
                        <div class="col inline l-9 m-10 s-12 product-animated-bottom">
                            <div class="t-global bold">Mitra Kami</div>
                            <div class="bdy-global center lh24">
                            </div>
                        </div>
                    </div>
                    <ul class="l-anggota product-animated-bottom">
                        <li>
                            <div class="i-anggota"><img class="img-anggota" src="{% static 'images/mitra/1.png' %}" />
                            </div>
                        </li>
                        <li>
                            <div class="i-anggota"><img class="img-anggota" src="{% static 'images/mitra/2.png' %}" />
                            </div>
                        </li>
                        <li>
                            <div class="i-anggota"><img class="img-anggota" src="{% static 'images/mitra/3.png' %}" />
                            </div>
                        </li>
                        <li>
                            <div class="i-anggota"><img class="img-anggota" src="{% static 'images/mitra/4.png' %}" />
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
</section>

<script type="text/javascript">
    $('header').addClass('sky');

    $('#main-menu ul li.menu-about, ul.resp-menu li.menu-about a').addClass('active');

    $('.slider-kegiatan').slick({
        autoplay: true,
        autoplaySpeed: 4000,
        slidesToShow: 3,
        centerPadding: '0',
        // centerMode: true,
        dot: false,
        arrows: true,
        focusOnSelect: false,
        infinite: true,
        slidesToScroll: 1,
        responsive: [{
            breakpoint: 992,
            settings: {
                slidesToShow: 4
            }
        }, {
            breakpoint: 768,
            settings: {
                slidesToShow: 2
            }
        }]
    });
    $("[data-fancybox]").fancybox({
        caption: function (instance, item) {
            return $(this).attr('title');
        },
        infobar: false,
        buttons: [
            'close'
        ],
        loop: true,
    });
</script>
{% endblock main %}