blogs/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index-blog'),
    path('<slug:slug>/', views.detail, name='detail-blog'),
]

travels/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index-travel'),
    path('<slug:slug>/', views.detail, name='detail-travel'),
]

website_umroh/urls.py

from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('tentang-kami/', include('abouts.urls')),
    path('travel/', include('travels.urls')),
    path('blog/', include('blogs.urls')),
    path('paket/', include('packages.urls')),
    path('', include('homes.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Administrasi Taufiq Harohmain Tobah"
admin.site.site_title = "TAUFIQ HT TOURS & TRAVEL"
handler404 = 'website_umroh.views.handler_404'
handler500 = 'website_umroh.views.handler_500'

travels/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from autoslug import AutoSlugField
from djmoney.models.fields import MoneyField



class TravelCategory(models.Model):
    nama = models.CharField(max_length=225)
    dibuat_pada = models.DateTimeField(auto_now_add=True)
    diperbarui_pada = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nama

    class Meta:
        ordering = ('nama',)
        verbose_name_plural = 'categories'  


class TravelFacility(models.Model):
    nama = models.CharField(max_length=225)
    dibuat_pada = models.DateTimeField(auto_now_add=True)
    diperbarui_pada = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nama

    class Meta:
        ordering = ('nama',)
        verbose_name_plural = 'facilities'


class TravelAirline(models.Model):
    nama = models.CharField(max_length=225)
    deskripsi = models.TextField(null=True, blank=True, help_text='Deskripsi airline / maskapai. Optional')
    dibuat_pada = models.DateTimeField(auto_now_add=True)
    diperbarui_pada = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nama
    
    class Meta:
        ordering = ('nama',)
        verbose_name_plural = 'airlines'


class AirlineImage(models.Model):
    airline = models.ForeignKey(TravelAirline, on_delete=models.CASCADE)
    img = models.ImageField(upload_to='travel/airline/img/', blank=True)
    dibuat_pada = models.DateTimeField(auto_now_add=True)
    diperbarui_pada = models.DateTimeField(auto_now=True)

    def __str__(self):
        return 'Image %s - %s' % (self.id, self.airline.nama)

    class Meta:
        ordering = ('id',)


class TravelHotel(models.Model):
    nama = models.CharField(max_length=225)
    deskripsi = models.TextField(null=True, blank=True, help_text='Deskripsi hotel. Optional')
    dibuat_pada = models.DateTimeField(auto_now_add=True)
    diperbarui_pada = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nama

    class Meta:
        ordering = ('nama',)
        verbose_name_plural = 'hotel'


class HotelImage(models.Model):
    hotel = models.ForeignKey(TravelHotel, on_delete=models.CASCADE)
    img = models.ImageField(upload_to='travel/hotel/img/', blank=True)
    dibuat_pada = models.DateTimeField(auto_now_add=True)
    diperbarui_pada = models.DateTimeField(auto_now=True)

    def __str__(self):
        return 'Image %s - %s' % (self.id, self.hotel.nama)

    class Meta:
        ordering = ('id',)


class Travel(models.Model):
    LABEL = [('populer', 'POPULER'),('promo', 'PROMO' )]
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='penulis')
    nama = models.CharField(max_length=250)
    kategori = models.ForeignKey(TravelCategory, on_delete=models.CASCADE)
    label = models.CharField(max_length=7, choices=LABEL, blank=True, help_text='Optional')
    harga = MoneyField(max_digits=14, decimal_places=2, default_currency='IDR')
    deskripsi = models.TextField(blank=True)
    fasilitas = models.ManyToManyField(TravelFacility, blank=True)
    penerbangan = models.ManyToManyField(TravelAirline, through='TravelFlight', blank=True)
    akomodasi = models.ManyToManyField(TravelHotel, through='TravelAccommodation', blank=True)
    dibuat_pada = models.DateTimeField(auto_now_add=True)
    diperbarui_pada = models.DateTimeField(auto_now=True)
    slug = AutoSlugField(populate_from='nama', unique=True, always_update=True)

    def __str__(self):
        return self.nama

    def get_absolute_url(self):
        return reverse('detail', kwargs={'slug': self.slug})

    class Meta:
        ordering = ('-id',)


class TravelImage(models.Model):
    paket = models.ForeignKey(Travel, on_delete=models.CASCADE)
    img = models.ImageField(upload_to='travel/img/', blank=True) 

    def __str__(self):
        return 'Gambar %s' % (self.id)

    class Meta:
        ordering = ('id',)
        verbose_name_plural = 'travel images'


class TravelFlight(models.Model):
    STATUS = [('berangkat', 'Berangkat'), ('kembali', 'Kembali')]
    paket = models.ForeignKey(Travel, on_delete=models.CASCADE)
    maskapai = models.ForeignKey(TravelAirline, on_delete=models.CASCADE, null=True, blank=True)
    status = models.CharField(choices=STATUS, max_length=9, null=True, blank=True, help_text='Status penerbangan berangkat / kembali. Optional')
    tanggal = models.DateField(null=True, blank=True, help_text='Tanggal penerbangan. Optional')

    def __str__(self):
        return '%s - %s' % (self.paket.nama, self.maskapai.nama)

    class Meta:
        ordering = ('paket',)
        verbose_name_plural = 'flights'


class TravelAccommodation(models.Model):
    paket = models.ForeignKey(Travel, on_delete=models.CASCADE)
    hotel = models.ForeignKey(TravelHotel, on_delete=models.CASCADE, null=True, blank=True)
    mulai_tanggal = models.DateField(null=True, blank=True, help_text='Tanggal mulai penginapan. Optional')
    akhir_tanggal = models.DateField(null=True, blank=True, help_text='Tanggal akhir penginapan. Optional')
    
    def __str__(self):
        return '%s - %s' % (self.paket.nama, self.hotel.nama)

    class Meta:
        ordering = ('paket',)
        verbose_name_plural = 'accomodations'


class TravelDetail(models.Model):
    paket = models.ForeignKey(Travel, on_delete=models.CASCADE)
    perjalanan = models.CharField(max_length=250)
    img = models.ImageField(upload_to='travel/traveldetail/img', blank=True)
    deskripsi = models.TextField(blank=True)

    def __str__(self):
        return "Perjalan: %s" % (self.perjalanan)

    class Meta:
        ordering = ('id',)

travels/views.py
from django.shortcuts import render,  get_object_or_404
from django.http import Http404

from .models import Travel, TravelCategory
from .filter import TravelFilter

from packages.models import PackageCategory

def index(request):
    travels = Travel.objects.all()
    category_travel = TravelCategory.objects.all()
    f = TravelFilter(request.GET, queryset=travels)

    category_package = PackageCategory.objects.all()
    template = 'travels/index.html'
    context = {
        'filter': f,
        'category_travel': category_travel,
        'category_package': category_package,
    }
    return render(request,template,context)

def detail(request, slug):
    travel = get_object_or_404(Travel, slug__iexact = slug)
    category_package = PackageCategory.objects.all()
    category_travel = TravelCategory.objects.all()
    template = 'travels/detail.html'
    context = {
        'travel': travel,
        'category_package': category_package,
        'category_travel': category_travel,
    }
    return render(request,template,context)

travels/templates/travels/filter.html
{% load static %}
{% load widget_tweaks %}

<form method="GET" class="form">
    <div class="jv-desti">
        <div class="mb-desti">
            <div class="pos-rel">
                {% render_field filter.form.n class="form-control" placeholder="Nama Travel" %}
                <div class="icon-cari">
                    <i class="fa fa-search" aria-hidden="true"></i>
                </div>
            </div><br/><br/>

            <div class="clear">
                <div class="inline992 pr20 mb-desti">
                    <div class="pos-rel">
                        <div class="icon-tag">
                            <img src="{% static 'images/icons/tag.png' %}" alt="icon_tag" />
                        </div>
                        <div class="kategori">
                            <span class="filter-option pull-left">Kategori</span>
                        </div>
                        {% render_field filter.form.k class="form-control" placeholder="Kategori" %}
                    </div>
                </div>
            </div><br/>

            <div class="clear">
                <div class="inline992 pr20 mb-desti">
                    <div class="pos-rel">
                        <div class="icon-kalender">
                            <img src="{% static 'images/icons/select-kalender.png' %}" alt="icon_kalender" />
                        </div>
                        <div class="dibuat_pada">
                            <span class="filter-option pull-left">Rentang tanggal pembuatan</span>
                        </div>
                        {% render_field filter.form.c class="form-control" readonly="true" style="background:#fff" %}
                    </div>
                </div>
            </div>
            <div align="center">
                <input type="submit" value="Cari Paket" class="button button--wapasha" />
            </div>
        </div>
    </div>    
</form>
<script>
    $(function() {
        $("#id_c_0").datepicker({
            dateFormat: 'dd-mm-yy',
            autoSize: true
        });
        $("#id_c_1").datepicker({
            dateFormat: 'dd-mm-yy',
            autoSize: true
        })
    })
</script>
        

travels/templates/travels/index.html
{% extends 'base.html' %}
{% load pagination_tags %}
{% load static %}

{% block style %}
    <link rel="stylesheet" type="text/css" href="{% static 'travels/css/styles.css' %}" />
{% endblock style %}
    

{% block main %}
<section id="main">
    <div class="pad-global">
        <div class="container">
            <div class="box-desti">
                <div class="title bold capitalize" id="result_destination">Semua Travel</div>
                <div class="bdr-desti"></div>
                <div class="row inline">

                    <div class="col inline l-3 m-12 s-12 sm30">
                        {% include './filter.html' %}
                    </div>

                    <div class="col inline l-9 m-12 s-12">
                        <div class="clear mb10">
                            <div class="float-left">
                                <div class="h34">
                                    <div class="tbl">
                                        <div class="cell">
                                            <div class="r-desti">{{ filter.qs.count }} Travel</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row inline min-10">

                            {% if filter.qs %}
                            {% autopaginate filter.qs 9 as filter_list %}
                            {% for obj in filter_list  %}
                            <div
                                class="col inline l-4 m-6 s-12 min-10 product-animated-bottom bevyup-top bevyup_product wrapHotOffer wrapLimited">
                                <div class=" item-desti">
                                    <div class="pos-rel">
                                        <a href="{% url 'detail-travel' obj.slug %}">
                                            <div class="overlay-desti"></div>
                                            <div class="img-desti"
                                                style="background: url('{{ obj.travelimage_set.first.img.url }}') no-repeat center;">
                                            </div>
                                            <div class="t-desti">{{ obj.nama }}</div>
                                        </a>
                                    </div>
                                    <div class="pos-rel">
                                        <div class="desc-desti">
                                            <div class="s-desti">Mulai</div><br />
                                            <div class="p-desti" style="color:#fdb813;">{{ obj.harga }}</div>
                                            <div class="l-desti">{{ obj.traveldetail_set.count }} Hari </div>
                                            <div class="bdy-desti">
                                                {{ obj.deskripsi |truncatechars:150|safe }}
                                            </div>
                                            <a href="{% url 'detail-travel' obj.slug %}" class="desti">
                                                Lihat Info <i class="fa fa-chevron-right" aria-hidden="true"></i>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                            {% else %}
                            <h4 class="text-center" style="margin-top: 5rem; color: #666">Travel belum ada</h4>
                            {% endif %}
                        </div>
                    </div>
                    <style>

                    </style>
                    <div id="pagination" class="col inline l-9 m-12 s-12">
                        {% paginate %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="bantuan" class="bg-help" style="background: url('lib/images/icons/bg-help.png') bottom no-repeat;">
        <div class="contanier">
            <div class="t-help bold">Anda Butuh Bantuan?</div>
            <div class="bdy-help">Hubungi kami untuk bantuan atau informasi lebih lanjut melalui line telepon</div>
            <div class="no-help">
                <a href="tel:6285863087879"> +6285863087879 </a><br />
                <a href="tel:6285797511206"> +6285797511206 </a><br />
            </div>
            <div class="bdy-help mb30">atau online form yang kami sediakan melalui tombol dibawah ini</div>
            <a class="contact"><button class="button button--wapasha btn-center">KONTAK KAMI</button></a>
        </div>
    </div>
</section>
{% endblock main %}